#!/usr/bin/env bash

# cwd
LLVM_PROJECT_ROOT=$(pwd)
LLVM_ROOT=${LLVM_PROJECT_ROOT}/llvm
BUILD_DIR=${LLVM_PROJECT_ROOT}/build

# Check for cmake
if ! command -v cmake &> /dev/null; then
    echo "cmake could not be found"
    exit
fi

# Check for Ninja
if ! command -v ninja &> /dev/null; then
    echo "Ninja could not be found"
    exit
fi

mkdir -p $BUILD_DIR

# Configure

cmake \
    -S $LLVM_ROOT \
    -B $BUILD_DIR \
    -G Ninja \
    -DCMAKE_BUILD_TYPE="Release" \
    -DLLVM_ENABLE_PROJECTS="clang" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS="1" \
    -DBUILD_SHARED_LIBS="Off" \
    -DLLVM_BUILD_LLVM_DYLIB="On" \
    -DLLVM_LINK_LLVM_DYLIB="On" \
    -DCLANG_LINK_CLANG_DYLIB="On" \
    -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="SCISA" \
    -DLLVM_TARGETS_TO_BUILD="" \
    -DLLVM_ENABLE_IDE="On" \
    -DLLVM_BUILD_TOOLS="Off" \
    -DLLVM_BUILD_TELEMETRY="Off" \
    -DLLVM_ENABLE_THREADS="Off" \
    -DLLVM_INCLUDE_BENCHMARKS="Off" \
    -DLLVM_INCLUDE_TESTS="Off" \
    -DLLVM_ENABLE_ASSERTIONS="On" \
    -DLLVM_BUILD_EXAMPLES="Off" \
    -DLLVM_TOOL_GOLD_BUILD="Off" \
    -DLLVM_TOOL_LLVM_AR_BUILD="Off" \
    -DLLVM_TOOL_LLVM_AS_BUILD="Off" \
    -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_COV_BUILD="Off" \
    -DLLVM_TOOL_LLVM_CTXPROF_UTIL_BUILD="Off" \
    -DLLVM_TOOL_LLVM_CVTRES_BUILD="Off" \
    -DLLVM_TOOL_LLVM_CXXDUMP_BUILD="Off" \
    -DLLVM_TOOL_LLVM_CXXFILT_BUILD="Off" \
    -DLLVM_TOOL_LLVM_CXXMAP_BUILD="Off" \
    -DLLVM_TOOL_LLVM_C_TEST_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DEBUGINFOD_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DEBUGINFOD_FIND_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DEBUGINFO_ANALYZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DIS_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DIS_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DLANG_DEMANGLE_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DWARFUTIL_BUILD="Off" \
    -DLLVM_TOOL_LLVM_DWP_BUILD="Off" \
    -DLLVM_TOOL_LLVM_GSYMUTIL_BUILD="Off" \
    -DLLVM_TOOL_LLVM_ISEL_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_ITANIUM_DEMANGLE_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_LIBTOOL_DARWIN_BUILD="Off" \
    -DLLVM_TOOL_LLVM_LTO2_BUILD="Off" \
    -DLLVM_TOOL_LLVM_LTO_BUILD="Off" \
    -DLLVM_TOOL_LLVM_MC_ASSEMBLE_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_MC_DISASSEMBLE_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_MICROSOFT_DEMANGLE_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_NM_BUILD="Off" \
    -DLLVM_TOOL_LLVM_OBJCOPY_BUILD="Off" \
    -DLLVM_TOOL_LLVM_OBJDUMP_BUILD="Off" \
    -DLLVM_TOOL_LLVM_OPT_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_OPT_REPORT_BUILD="Off" \
    -DLLVM_TOOL_LLVM_PDBUTIL_BUILD="Off" \
    -DLLVM_TOOL_LLVM_PROFDATA_BUILD="Off" \
    -DLLVM_TOOL_LLVM_PROFGEN_BUILD="Off" \
    -DLLVM_TOOL_LLVM_RC_BUILD="Off" \
    -DLLVM_TOOL_LLVM_READOBJ_BUILD="Off" \
    -DLLVM_TOOL_LLVM_RUST_DEMANGLE_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_SPECIAL_CASE_LIST_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_YAML_NUMERIC_PARSER_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LLVM_YAML_PARSER_FUZZER_BUILD="Off" \
    -DLLVM_TOOL_LTO_BUILD="Off" \
    -DLLVM_TOOL_SANCOV_BUILD="Off" \
    -DLLVM_TOOL_SANSTATS_BUILD="Off" \
    -DLLVM_TOOL_SPIRV_TOOLS_BUILD="Off" \
    -DLLVM_TOOL_VFABI_DEMANGLE_FUZZER_BUILD="Off"

cd $BUILD_DIR && ninja

